In [1]:
import numpy as np
from grabscreen import grab_screen
import cv2
import time
from directkeys import PressKey,ReleaseKey, W, A, S, D
from alexnet import alexnet
from getkeys import key_check

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
import random

WIDTH = 160
HEIGHT = 120
LR = 1e-3
EPOCHS = 10
MODEL_NAME = 'pynfs5-car-fast-{}-{}-{}-epochs-2K-data.model'.format(LR, 'alexnetv2',EPOCHS)
#MODEL_NAME = 'pynfs5-car-fast-0.001-alexnetv2-10-epochs-2K-data.model'

In [3]:
t_time = 0.09

def straight():
##    if random.randrange(4) == 2:
##        ReleaseKey(W)
##    else:
    PressKey(W)
    ReleaseKey(A)
    ReleaseKey(D)

def left():
    PressKey(W)
    PressKey(A)
    #ReleaseKey(W)
    ReleaseKey(D)
    #ReleaseKey(A)
    time.sleep(t_time)
    ReleaseKey(A)

def right():
    PressKey(W)
    PressKey(D)
    ReleaseKey(A)
    #ReleaseKey(W)
    #ReleaseKey(D)
    time.sleep(t_time)
    ReleaseKey(D)

In [4]:
model = alexnet(WIDTH, HEIGHT, LR)
model.load(MODEL_NAME)

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Use tf.initializers.variance_scaling instead with distribution=uniform to get equivalent behavior.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
INFO:tensorflow:Restoring parameters from C:\Users\user\Desktop\projects\Swamchalak Vahan\PROJECT\Alexnet Caar\pynfs5-car-fast-0.001-alexnetv2-10-epochs-2K-data.model


In [5]:
def main():
    last_time = time.time()
    for i in list(range(4))[::-1]:
        print(i+1)
        time.sleep(1)

    paused = False
    while(True):
        
        if not paused:
            # 800x600 windowed mode
            #screen =  np.array(ImageGrab.grab(bbox=(0,40,800,640)))
            screen = grab_screen(region=(120,120,730,580))
            print('loop took {} seconds'.format(time.time()-last_time))
            last_time = time.time()
            screen = cv2.cvtColor(screen, cv2.COLOR_BGR2GRAY)
            screen = cv2.resize(screen, (160,120))

            prediction = model.predict([screen.reshape(160,120,1)])[0]
            print(prediction)

            turn_thresh = .75
            fwd_thresh = 0.70

            if prediction[1] > fwd_thresh:
                straight()
            elif prediction[0] > turn_thresh:
                left()
            elif prediction[2] > turn_thresh:
                right()
            else:
                straight()

        keys = key_check()

        # p pauses game and can get annoying.
        if 'T' in keys:
            if paused:
                paused = False
                time.sleep(1)
            else:
                paused = True
                ReleaseKey(A)
                ReleaseKey(W)
                ReleaseKey(D)
                time.sleep(1)

In [ ]:
main()

4
3
2
1
loop took 6.038814306259155 seconds
[0.00267291 0.01771031 0.97961676]
loop took 10.210007667541504 seconds
[0.00247304 0.0128341  0.9846928 ]
loop took 0.22294878959655762 seconds
[0.00163008 0.01366711 0.98470277]
loop took 0.26889944076538086 seconds
[0.00237118 0.01214595 0.98548293]
loop took 0.32908082008361816 seconds
[0.00161685 0.00411432 0.9942688 ]
loop took 0.2770693302154541 seconds
[0.00216282 0.00451143 0.9933257 ]
loop took 0.3031775951385498 seconds
[0.00224411 0.00377104 0.9939849 ]
loop took 0.28261685371398926 seconds
[0.00263088 0.00440696 0.9929622 ]
loop took 0.263899564743042 seconds
[0.00211371 0.00402121 0.9938651 ]
loop took 0.29583191871643066 seconds
[0.0021908  0.00372494 0.9940843 ]
loop took 0.2708475589752197 seconds
[0.00230677 0.00733658 0.9903566 ]
loop took 0.2771613597869873 seconds
[0.00356151 0.01825815 0.9781804 ]
loop took 0.28316259384155273 seconds
[0.00638911 0.05429796 0.9393129 ]
loop took 0.24951767921447754 seconds
[0.09031159 0.

loop took 0.3333256244659424 seconds
[0.04740168 0.02575102 0.92684734]
loop took 0.35592150688171387 seconds
[0.01165352 0.04438316 0.9439633 ]
loop took 0.267179012298584 seconds
[0.06664898 0.02629241 0.90705866]
loop took 0.30286455154418945 seconds
[0.9745534  0.00676385 0.01868265]
loop took 0.3758056163787842 seconds
[9.9940765e-01 1.5826148e-04 4.3415450e-04]
loop took 0.3774998188018799 seconds
[0.9862584  0.00749213 0.00624947]
loop took 0.31992220878601074 seconds
[0.04299352 0.5212088  0.43579766]
loop took 0.19840526580810547 seconds
[0.00522827 0.16083571 0.833936  ]
loop took 0.2899188995361328 seconds
[0.01762233 0.05664033 0.9257374 ]
loop took 0.2827763557434082 seconds
[0.01194539 0.04179304 0.9462616 ]
loop took 0.3689155578613281 seconds
[0.00644815 0.00637711 0.98717475]
loop took 0.3593893051147461 seconds
[0.00137102 0.00505458 0.99357444]
loop took 0.28183579444885254 seconds
[6.2646804e-04 8.4274244e-03 9.9094617e-01]
loop took 0.3024628162384033 seconds
[0.00

[0.08281495 0.03287992 0.8843052 ]
loop took 0.3393526077270508 seconds
[0.01997223 0.01546298 0.9645648 ]
loop took 0.2625899314880371 seconds
[0.02132952 0.02353403 0.9551364 ]
loop took 0.3574686050415039 seconds
[0.9425469  0.03383262 0.02362045]
loop took 0.336383581161499 seconds
[0.95560396 0.04082581 0.00357027]
loop took 0.3450446128845215 seconds
[0.97380733 0.02247902 0.00371358]
loop took 0.3474709987640381 seconds
[0.89133483 0.10296926 0.00569588]
loop took 0.3067760467529297 seconds
[9.9836916e-01 6.4299733e-04 9.8787842e-04]
loop took 0.31786251068115234 seconds
[0.4228823  0.03232605 0.54479164]
loop took 0.24192523956298828 seconds
[0.01694925 0.01420623 0.9688445 ]
loop took 0.36674022674560547 seconds
[0.00128308 0.00127246 0.9974445 ]
loop took 0.3189401626586914 seconds
[0.0022428  0.00424017 0.99351704]
loop took 0.3103973865509033 seconds
[0.81174195 0.02834034 0.15991771]
loop took 0.39084792137145996 seconds
[0.9968285  0.00188564 0.00128591]
loop took 0.42828

[0.4384847  0.00657252 0.55494285]
loop took 0.21048426628112793 seconds
[0.70964426 0.0026209  0.2877349 ]
loop took 0.15990972518920898 seconds
[0.44476026 0.00860294 0.5466368 ]
loop took 0.17742490768432617 seconds
[0.64762115 0.00532314 0.34705573]
loop took 0.13479304313659668 seconds
[0.2535393  0.00906225 0.73739845]
loop took 0.2134385108947754 seconds
[0.05455781 0.00471072 0.94073147]
loop took 0.29733872413635254 seconds
[2.3655515e-02 3.7151235e-04 9.7597301e-01]
loop took 0.25395846366882324 seconds
[1.1999928e-02 3.0175786e-04 9.8769838e-01]
loop took 0.21439337730407715 seconds
[1.1999928e-02 3.0175786e-04 9.8769838e-01]
loop took 0.2248706817626953 seconds
[1.1999928e-02 3.0175786e-04 9.8769838e-01]
loop took 0.3088243007659912 seconds
[5.4557682e-03 4.2049750e-04 9.9412376e-01]
loop took 0.338839054107666 seconds
[0.06001288 0.0165815  0.9234056 ]
loop took 0.3088502883911133 seconds
[0.03405394 0.00411527 0.9618308 ]
loop took 0.33749938011169434 seconds
[0.02751847 

loop took 0.28942441940307617 seconds
[0.05177201 0.02544245 0.9227856 ]
loop took 0.32581472396850586 seconds
[0.05736204 0.01621672 0.9264212 ]
loop took 0.4010586738586426 seconds
[0.02864291 0.00213397 0.96922314]
loop took 0.316342830657959 seconds
[0.57240313 0.03448071 0.3931162 ]
loop took 0.24590659141540527 seconds
[0.43471012 0.19966455 0.36562538]
loop took 0.20687103271484375 seconds
[0.884744   0.01194011 0.10331596]
loop took 0.341505765914917 seconds
[0.96160287 0.02959803 0.00879918]
loop took 0.2800023555755615 seconds
[0.20187058 0.04948076 0.74864864]
loop took 0.19097685813903809 seconds
[0.02774785 0.00886675 0.9633854 ]
loop took 0.3181328773498535 seconds
[0.01458587 0.01943123 0.9659829 ]
loop took 0.31195592880249023 seconds
[0.0189226  0.06668264 0.91439474]
loop took 0.321338415145874 seconds
[0.15750398 0.09423941 0.7482566 ]
loop took 0.22831082344055176 seconds
[0.5505107  0.41708496 0.03240442]
loop took 0.18499398231506348 seconds
[0.88348955 0.09258419

loop took 0.3044905662536621 seconds
[0.01380398 0.15618852 0.83000755]
loop took 0.377810001373291 seconds
[0.01454495 0.2738786  0.7115764 ]
loop took 0.19501638412475586 seconds
[0.02778537 0.5782562  0.39395845]
loop took 0.2560081481933594 seconds
[0.03501734 0.31260368 0.6523789 ]
loop took 0.18902873992919922 seconds
[0.04859738 0.1469395  0.8044631 ]
loop took 0.2808396816253662 seconds
[0.01406212 0.09843986 0.887498  ]
loop took 0.34894514083862305 seconds
[0.7450878  0.22635196 0.02856021]
loop took 0.18511462211608887 seconds
[9.8059148e-01 1.9081581e-02 3.2697289e-04]
loop took 0.2753596305847168 seconds
[9.5090574e-01 4.8196528e-02 8.9783769e-04]
loop took 0.3474690914154053 seconds
[0.63560295 0.3519449  0.01245213]
loop took 0.20641613006591797 seconds
[0.02028446 0.17553425 0.8041813 ]
loop took 0.3103971481323242 seconds
[0.00119904 0.0762623  0.92253864]
loop took 0.35180044174194336 seconds
[0.01065028 0.18295066 0.80639905]
loop took 0.32192015647888184 seconds
[0.

[0.8057469  0.02062719 0.17362589]
loop took 0.32149791717529297 seconds
[0.43885726 0.04389248 0.5172503 ]
loop took 0.20623540878295898 seconds
[0.11020164 0.01742281 0.87237555]
loop took 0.3722267150878906 seconds
[0.02737761 0.00106632 0.971556  ]
loop took 0.49004101753234863 seconds
[1.9680159e-03 5.2295445e-04 9.9750900e-01]
loop took 0.36499571800231934 seconds
[1.1505235e-03 6.8849692e-04 9.9816102e-01]
loop took 0.30134034156799316 seconds
[0.00325672 0.00513696 0.99160635]
loop took 0.3474085330963135 seconds
[0.01386831 0.00681067 0.979321  ]
loop took 0.31702685356140137 seconds
[0.10372475 0.01341108 0.8828642 ]
loop took 0.3259115219116211 seconds
[0.29257622 0.02477005 0.6826537 ]
loop took 0.13414311408996582 seconds
[0.57176936 0.01837014 0.40986052]
loop took 0.2180483341217041 seconds
[0.88079125 0.03438069 0.08482806]
loop took 0.3133354187011719 seconds
[0.94304377 0.0044118  0.05254451]
loop took 0.3150019645690918 seconds
[0.97222364 0.00383123 0.0239451 ]
loop

loop took 0.09494519233703613 seconds
[0.622041   0.00453259 0.37342644]
loop took 0.08395195007324219 seconds
[0.6216073  0.0049825  0.37341017]
loop took 0.10094451904296875 seconds
[0.60353863 0.0043934  0.392068  ]
loop took 0.1019434928894043 seconds
[0.6227616  0.00478627 0.37245217]
loop took 0.11493301391601562 seconds
[0.63326234 0.00455141 0.36218622]
loop took 0.10094380378723145 seconds
[0.61504334 0.0049558  0.38000086]
loop took 0.09894776344299316 seconds
[0.61716574 0.00487997 0.37795436]
loop took 0.09294915199279785 seconds
[0.61583865 0.00498527 0.37917608]
loop took 0.10194611549377441 seconds
[0.626068   0.00518373 0.3687483 ]
loop took 0.0969395637512207 seconds
[0.62254757 0.00519221 0.37226024]
loop took 0.08195304870605469 seconds
[0.63428766 0.00581048 0.3599019 ]
loop took 0.08363628387451172 seconds
[0.62615603 0.00620194 0.36764205]
loop took 0.08595108985900879 seconds
[0.6145617  0.00553746 0.3799008 ]
loop took 0.1019439697265625 seconds
[0.64128995 0.00